communication/urls.py
from django.urls import path

from communication.apps import CommunicationConfig
from communication.views import (
    CommunicationCreateView,
    CommunicationDeleteView,
    CommunicationDetailView,
    CommunicationListView,
    CommunicationUpdateView,
)

app_name = CommunicationConfig.name

urlpatterns = [
    path("communication", CommunicationListView.as_view(), name="communication_list"),
    path(
        "communication/create/",
        CommunicationCreateView.as_view(),
        name="communication_create",
    ),
    path(
        "communication/<int:pk>/",
        CommunicationDetailView.as_view(),
        name="communication_detail",
    ),
    path(
        "communication/<int:pk>/update/",
        CommunicationUpdateView.as_view(),
        name="communication_update",
    ),
    path(
        "communication/<int:pk>/delete/",
        CommunicationDeleteView.as_view(),
        name="communication_delete",
    ),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailing.urls", namespace="mailing")),
    path("client/", include("client.urls", namespace="client")),
    path("communication/", include("communication.urls", namespace="communication")),
    path("users/", include("users.urls", namespace="urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
)
from django.urls import path

from users.apps import UsersConfig
from users.views import CustomPasswordResetView, UserCreatorView, email_verification

app_name = UsersConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserCreatorView.as_view(), name="register"),
    path("email-confirm/<str:token>/", email_verification, name="email-confirm"),
    path("password_reset/", CustomPasswordResetView.as_view(), name="password_reset"),
    path(
        "password_reset/done/",
        PasswordResetDoneView.as_view(template_name="password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(template_name="password_reset_confirm.html"),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        PasswordResetCompleteView.as_view(template_name="password_reset_complete.html"),
        name="password_reset_complete",
    ),
]

communication/models.py
from django.db import models

from users.models import User


class Communication(models.Model):
    topic = models.CharField(
        max_length=100,
        verbose_name="Тема сообщения",
        help_text="Укажите тему сообщения",
    )
    links = models.TextField(
        verbose_name="Текст сообщения", help_text="Добавьте текст сообщения"
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Дата создания",
        help_text="Дата создания продукта",
    )

    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name="Дата последнего изменения",
        help_text="Дата последнего изменения продукта",
    )
    owner = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="communications",
        verbose_name="Владелец",
        blank=True,
        null=True,
    )

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщенния"

    def __str__(self):
        return self.topic

communication/forms.py
from django.forms import ModelForm

from communication.models import Communication


class CommunicationForm(ModelForm):
    class Meta:
        model = Communication
        exclude = ("owner",)

communication/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.cache import cache
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from communication.forms import CommunicationForm
from communication.models import Communication


class CommunicationListView(LoginRequiredMixin, ListView):
    model = Communication
    template_name = "communication_list.html"

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.is_superuser:
            return queryset
        else:
            return queryset.filter(owner=self.request.user)


@method_decorator(cache_page(60 * 15), name="dispatch")
class CommunicationDetailView(LoginRequiredMixin, DetailView):
    model = Communication
    template_name = "communication_detail.html"


class CommunicationCreateView(LoginRequiredMixin, CreateView):
    model = Communication
    form_class = CommunicationForm
    template_name = "communication_form.html"
    success_url = reverse_lazy("communication:communication_list")

    def form_valid(self, form):
        communication = form.save()
        communication.owner = self.request.user
        return super().form_valid(form)


class CommunicationUpdateView(LoginRequiredMixin, UpdateView):
    model = Communication
    form_class = CommunicationForm
    template_name = "communication_form.html"
    success_url = reverse_lazy("communication:communication_list")


class CommunicationDeleteView(LoginRequiredMixin, DeleteView):
    model = Communication
    template_name = "communication_confirm_delete.html"
    success_url = reverse_lazy("communication:communication_list")

communication/templates/communication_confirm_delete.html
{% extends 'client/base.html' %}
{% block title %} Удаление сообщения {% endblock %}
{% block content %}
 <div class="container h-100 d-flex align-items-center justify-content-center">
     <div class="row justify-content-center">
         <div class="col-6">
             <form class="row" method="post" enctype="multipart/form-data">
                 <div class="card text-center mt-2">
                     <div class="card-header">
                         <h5 class="card-title mt-2" style="min-height: 40px;">
                             Вы действительно хотите удалить сообщение "{{ object.topic }}"?</h5>
                     </div>
                     <div class="card-body d-flex flex-column align-items-center justify-content-center">
                         {% csrf_token %}
                     </div>
                     <div class="mt-auto">
                         <a class="btn btn-primary" href="{% url 'communication:communication_detail' object.pk %}" role="button">Отмена</a>
                         <button type="submit" class="btn btn-danger ">Удалить</button>
                     </div>
                 </div>
             </form>
         </div>
     </div>
 </div>
{% endblock %}

communication/templates/communication_detail.html
{% extends 'client/base.html' %}
{% block title %}Сообщение{% endblock %}
{% block content %}

<h1 class="text-center">{{ object.topic }}</h1>
<p>Текст сообщения: {{ object.links }}</p>

<div class="mt-4">
    <a class="btn btn-outline-primary" href="{% url 'communication:communication_update' object.pk %}" role="button">Редактировать</a>
    <a class="btn btn-outline-danger" href="{% url 'communication:communication_delete' object.pk %}" role="button">Удалить</a>
</div>


<p>Последнее изменение: {{ object.updated_at }}</p>
<p>Добавлено: {{ object.created_at }}</p>

{% endblock %}

communication/templates/communication_form.html
{% extends 'client/base.html' %}
{% block title %} {% if object %}
Редактирование сообщения
{% else %}
Новое сообщение
{% endif %} {% endblock %}
{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header text-center" >
                <h5 class="card-title mt-2" style="min-height: 40px;">
                    {% if object %}
                    Редактирование сообщения
                    {% else %}
                    Новое сообщение
                    {% endif %}
                </h5>
            </div>
            <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Сохранить</button>
                        <button type="button" class="btn btn-danger ml-2">
        <a class="text-white" href="{% url 'communication:communication_list' %}">Отмена</a>
    </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

communication/templates/communication_list.html
{% extends 'client/base.html' %}
{% load static %}
{% block title %} Список сообщений {% endblock %}
{% block content %}

<h1 class="text-center mt-3">Список сообщений</h1>
{% if user.is_authenticated %}
{% if object_list %}
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Тема</th>
            <th>Сообщение</th>
            <th>Последнее изменение</th>
        </tr>
    </thead>
    <tbody>
        {% for communication in object_list %}
        <tr>
            <td>
                {{ communication.topic }}
            </td>
            <td>
                {{ communication.links }}
            </td>
            <td>
                <small>Последнее изменение: {{ communication.updated_at|timesince }} назад</small>
                <a class="text-primary" href="{% url 'communication:communication_detail' communication.id %}" style="cursor: pointer;">Подробнее</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
    <p class="text-center">К сожалению, список сообщений пуст.</p>
{% endif %}

<div class="text-center mt-3">
    <a class="btn btn-secondary text-white" href="{% url 'communication:communication_create' %}">Создать новое сообщение</a>
</div>
{% else %}
    <p>Пожалуйста, <a href="{% url 'users:login' %}">войдите</a>, чтобы увидеть список своих сообщений.</p>
{% endif %}
{% endblock %}