client/urls.py
from django.urls import path

from client.apps import ClientConfig
from client.views import (
    ClientCreateView,
    ClientDeleteView,
    ClientDetailView,
    ClientListView,
    ClientUpdateView,
)

app_name = ClientConfig.name

urlpatterns = [
    path("communication/", ClientListView.as_view(), name="client_list"),
    path("communication/create/", ClientCreateView.as_view(), name="client_create"),
    path("communication/<int:pk>/", ClientDetailView.as_view(), name="client_detail"),
    path(
        "communication/<int:pk>/update/",
        ClientUpdateView.as_view(),
        name="client_update",
    ),
    path(
        "communication/<int:pk>/delete/",
        ClientDeleteView.as_view(),
        name="client_delete",
    ),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailing.urls", namespace="mailing")),
    path("client/", include("client.urls", namespace="client")),
    path("communication/", include("communication.urls", namespace="communication")),
    path("users/", include("users.urls", namespace="urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
)
from django.urls import path

from users.apps import UsersConfig
from users.views import CustomPasswordResetView, UserCreatorView, email_verification

app_name = UsersConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserCreatorView.as_view(), name="register"),
    path("email-confirm/<str:token>/", email_verification, name="email-confirm"),
    path("password_reset/", CustomPasswordResetView.as_view(), name="password_reset"),
    path(
        "password_reset/done/",
        PasswordResetDoneView.as_view(template_name="password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(template_name="password_reset_confirm.html"),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        PasswordResetCompleteView.as_view(template_name="password_reset_complete.html"),
        name="password_reset_complete",
    ),
]

client/models.py
from django.db import models

from users.models import User


class Client(models.Model):
    email = models.EmailField(
        unique=True,
        verbose_name="Адрес электронной почты",
        help_text="Укажите адрес электронной почты для связи",
    )
    name = models.CharField(
        max_length=100,
        blank=True,
        null=True,
        verbose_name="Имя клиента",
        help_text="Укажите имя клиента",
    )
    comment = models.TextField(
        blank=True,
        null=True,
        verbose_name="Комментарий клиента",
        help_text="Добавьте любые дополнительные комментарии к клиенту",
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Дата создания",
        help_text="Дата создания продукта",
    )

    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name="Дата последнего изменения",
        help_text="Дата последнего изменения продукта",
    )
    owner = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="clients",
        verbose_name="Владелец",
        blank=True,
        null=True,
    )

    class Meta:
        verbose_name = "Клиент"
        verbose_name_plural = "Клиенты"

    def __str__(self):
        return self.email

client/forms.py
from django.forms import ModelForm

from client.models import Client


class ClientForm(ModelForm):
    class Meta:
        model = Client
        exclude = ("owner",)

client/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.cache import cache
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from client.forms import ClientForm
from client.models import Client


class ClientListView(LoginRequiredMixin, ListView):
    model = Client
    template_name = "communication/client_list.html"

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.is_superuser:
            return queryset
        else:
            return queryset.filter(owner=self.request.user)


@method_decorator(cache_page(60 * 15), name="dispatch")
class ClientDetailView(LoginRequiredMixin, DetailView):
    model = Client


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy("communication:client_list")

    def form_valid(self, form):
        client = form.save()
        client.owner = self.request.user
        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy("communication:client_list")


class ClientDeleteView(DeleteView):
    model = Client
    success_url = reverse_lazy("communication:client_list")

client/templates/client/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Описание вашего сайта.">
    <meta name="keywords" content="ключевые, слова, вашего, сайта">
    {% load static %}
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <title>{% block title %}Мой сайт{% endblock %}</title>
</head>
<body>
<div class="container">
    <div class="row">
        {% include 'client/includes/inc_menu.html' %}
        {% block content %}{% endblock %}
    </div>
</div>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>


<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

client/templates/client/client_confirm_delete.html
{% extends 'client/base.html' %}
{% block title %} Удаление клиента {% endblock %}
{% block content %}
 <div class="container h-100 d-flex align-items-center justify-content-center">
     <div class="row justify-content-center">
         <div class="col-6">
             <form class="row" method="post" enctype="multipart/form-data">
                 <div class="card text-center mt-2">
                     <div class="card-header">
                         <h5 class="card-title mt-2" style="min-height: 40px;">
                             Вы действительно хотите удалить клиента "{{ object.name }}"?</h5>
                     </div>
                     <div class="card-body d-flex flex-column align-items-center justify-content-center">
                         {% csrf_token %}
                     </div>
                     <div class="mt-auto">
                         <a class="btn btn-primary" href="{% url 'client:client_detail' object.pk %}" role="button">Отмена</a>
                         <button type="submit" class="btn btn-danger ">Удалить</button>
                     </div>
                 </div>
             </form>
         </div>
     </div>
 </div>
{% endblock %}

client/templates/client/client_detail.html
{% extends 'client/base.html' %}
{% block title %}Профиль клиента | {{ object.name }}{% endblock %}
{% block content %}

<h1 class="text-center">{{ object.name }}</h1>
<p class="mt-3">E-mail: <a href="mailto:{{ object.email }}">{{ object.email }}</a></p>
<p>Комментарий: {{ object.comment }}</p>

<div class="mt-4">
    <a class="btn btn-outline-primary" href="{% url 'client:client_update' client.pk %}" role="button">Редактировать</a>
    <a class="btn btn-outline-danger" href="{% url 'client:client_delete' client.pk %}" role="button">Удалить</a>
</div>


<p>Последнее изменение: {{ object.updated_at }}</p>
<p>Добавлен: {{ object.created_at }}</p>

{% endblock %}

client/templates/client/client_form.html
{% extends 'client/base.html' %}
{% block title %} {% if object %}
Редактирование клиента
{% else %}
Новый клиент
{% endif %} {% endblock %}
{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header text-center" >
                <h5 class="card-title mt-2" style="min-height: 40px;">
                    {% if object %}
                    Редактирование клиента
                    {% else %}
                    Новый клиент
                    {% endif %}
                </h5>
            </div>
            <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Сохранить</button>
                        <button type="button" class="btn btn-danger ml-2">
        <a class="text-white" href="{% url 'client:client_list' %}">Отмена</a>
    </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

client/templates/client/client_list.html
{% extends 'client/base.html' %}
{% load static %}
{% block title %} Список клиентов {% endblock %}
{% block content %}

<h1 class="text-center mt-3">Список клиентов</h1>
{% if user.is_authenticated %}
{% if object_list %}
<table class="table table-bordered">
    <thead>
    <tr>
        <th>Ф.И.О.</th>
        <th>e-mail</th>
        <th>Последнее изменение</th>
    </tr>
    </thead>
    <tbody>
    {% for client in object_list %}
    <tr>
        <td>
            {% if client.picture %}
            <img src="{{ client.picture.url }}" class="img-fluid" alt="{{ client.name }}"
                 style="height: 50px; object-fit: cover; display: inline-block; margin-right: 10px;">
            {% endif %}
            {{ client.name }}
        </td>
        <td>
            <a href="mailto:{{ client.email }}">{{ client.email }}</a>
        </td>
        <td>
            <small>Последнее изменение: {{ client.updated_at|timesince }} назад</small>
            <span class="text-primary" style="cursor: pointer;"
                  onclick="window.location.href='{% url 'client:client_detail' client.pk %}'">Подробнее</span>

        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% else %}
<p class="text-center">Список клиентов пуст.</p>
{% endif %}
<div class="text-center mt-3">
    <a class="btn btn-secondary text-white" href="{% url 'client:client_create' %}">Создать нового клиента</a>

</div>
{% else %}
<p>Пожалуйста, <a href="{% url 'users:login' %}">войдите</a>, чтобы увидеть список своих клиентов.</p>
{% endif %}
{% endblock %}