config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailing.urls", namespace="mailing")),
    path("client/", include("client.urls", namespace="client")),
    path("communication/", include("communication.urls", namespace="communication")),
    path("users/", include("users.urls", namespace="urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path

from mailing.apps import MailingConfig
from mailing.views import (
    HomeView,
    MailingCreateView,
    MailingDeleteView,
    MailingDetailView,
    MailingListView,
    MailingUpdateView,
    SendMailingView,
)

app_name = MailingConfig.name

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("mailing/", MailingListView.as_view(), name="mailing_list"),
    path("mailing/create/", MailingCreateView.as_view(), name="mailing_create"),
    path("mailing/<int:pk>/", MailingDetailView.as_view(), name="mailing_detail"),
    path(
        "mailing/<int:pk>/update/", MailingUpdateView.as_view(), name="mailing_update"
    ),
    path(
        "mailing/<int:pk>/delete/", MailingDeleteView.as_view(), name="mailing_delete"
    ),
    path("mailing/send/<int:pk>/", SendMailingView.as_view(), name="send_mailing"),
]

users/urls.py
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
)
from django.urls import path

from users.apps import UsersConfig
from users.views import CustomPasswordResetView, UserCreatorView, email_verification

app_name = UsersConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserCreatorView.as_view(), name="register"),
    path("email-confirm/<str:token>/", email_verification, name="email-confirm"),
    path("password_reset/", CustomPasswordResetView.as_view(), name="password_reset"),
    path(
        "password_reset/done/",
        PasswordResetDoneView.as_view(template_name="password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(template_name="password_reset_confirm.html"),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        PasswordResetCompleteView.as_view(template_name="password_reset_complete.html"),
        name="password_reset_complete",
    ),
]

mailing/models.py
from django.db import models

from client.models import Client
from communication.models import Communication
from users.models import User


class Mailing(models.Model):
    status_choice = [
        ("Создана", "Создана"),
        ("Запущена", "Запущена"),
        ("Завершена", "Завершена"),
    ]
    first_send_time = models.DateTimeField(
        null=True, blank=True, verbose_name="Начало рассылки"
    )
    end_time = models.DateTimeField(
        null=True, blank=True, verbose_name="Окончание рассылки"
    )
    status = models.CharField(
        max_length=20, choices=status_choice, default="Создана", verbose_name="Статус"
    )
    communication = models.ForeignKey(
        Communication, on_delete=models.CASCADE, verbose_name="Сообщение"
    )
    client = models.ManyToManyField(Client, verbose_name="Клиенты")
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Дата создания",
        help_text="Дата создания продукта",
    )

    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name="Дата последнего изменения",
        help_text="Дата последнего изменения продукта",
    )
    owner = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="mailings",
        verbose_name="Владелец",
        null=True,
        blank=True,
    )

    class Meta:
        verbose_name = "Рассылка"
        verbose_name_plural = "Рассылки"

    def __str__(self):
        return f"Рассылка: {self.communication.subject} - {self.status}"


class MailingAttempt(models.Model):
    status_choice = [
        ("Успешно", "Успешно"),
        ("Не успешно", "Не успешно"),
    ]

    timestamp = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата и время попытки"
    )
    status = models.CharField(
        max_length=20, choices=status_choice, verbose_name="Статус "
    )
    server_response = models.TextField(verbose_name="Ответ почтового сервера")
    mailing = models.ForeignKey(
        Mailing,
        on_delete=models.CASCADE,
        related_name="attempts",
        verbose_name="Рассылка",
    )

    class Meta:
        verbose_name = "Попытка рассылки"
        verbose_name_plural = "Попытки рассылки"

    def __str__(self):
        return f"{self.timestamp} - {self.status}"


# class EmailStatistics(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     successful_attempts = models.IntegerField(default=0)
#     failed_attempts = models.IntegerField(default=0)
#     total_sent = models.IntegerField(default=0)
#
#     class Metta:
#         verbose_name = "Статистика рассылки"
#         verbose_name_plural = "Статистики рассылки"
#
#     def __str__(self):
#         return f"Статистика для {self.user.email}"

mailing/forms.py
from django.forms import ModelForm

from mailing.models import Mailing


class MailingForm(ModelForm):
    class Meta:
        model = Mailing
        exclude = ("owner",)

mailing/views.py
import os

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, render
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.cache import cache_page
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)
from dotenv import load_dotenv

from client.models import Client
from mailing.forms import MailingForm
from mailing.models import Mailing

load_dotenv()


class MailingListView(LoginRequiredMixin, ListView):
    model = Mailing
    template_name = "mailing_list.html"

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.is_superuser:
            return queryset
        else:
            return queryset.filter(owner=self.request.user)


@method_decorator(cache_page(60 * 15), name="dispatch")
class MailingDetailView(LoginRequiredMixin, DetailView):
    model = Mailing
    template_name = "mailing_detail.html"

    # @login_required
    # def disable_mailing(request, mailing_id):
    #     if not can_disable_mailings(request.user):
    #         return redirect("unauthorized")
    #     mailing = get_object_or_404(Mailing, id=mailing_id)
    #     mailing.is_active = False
    #     mailing.save()
    #     return redirect("mailing_list")


class MailingCreateView(LoginRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForm
    success_url = "/"
    template_name = "mailing_form.html"

    def form_valid(self, form):
        mailing = form.save()
        mailing.owner = self.request.user
        return super().form_valid(form)


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    model = Mailing
    form_class = MailingForm
    success_url = "/"
    template_name = "mailing_form.html"


class MailingDeleteView(LoginRequiredMixin, DeleteView):
    model = Mailing
    success_url = "/"
    template_name = "mailing_confirm_delete.html"


class SendMailingView(LoginRequiredMixin, View):
    def post(self, request, pk):
        mailing = get_object_or_404(Mailing, pk=pk)
        clients = Client.objects.all()
        client_emails = [client.email for client in clients]

        try:
            send_mail(
                subject=mailing.communication.topic,
                message=mailing.communication.links,
                from_email=os.getenv("EMAIL_HOST_USER"),
                recipient_list=client_emails,
                fail_silently=False,
            )
            messages.success(request, "Рассылка успешно отправлена!")
        except Exception as e:
            messages.error(request, f"Ошибка при отправке рассылки: {str(e)}")

        return render(
            request, "result.html", {"message": "Рассылка успешно отправлена!"}
        )


class HomeView(View):
    def get(self, request):
        total_mailings = Mailing.objects.count()
        active_mailings = Mailing.objects.filter(status="Запущена").count()
        unique_recipients = Client.objects.values("email").distinct().count()

        context = {
            "total_mailings": total_mailings,
            "active_mailings": active_mailings,
            "unique_recipients": unique_recipients,
        }

        return render(request, "home.html", context)


# class EmailStatisticsView(LoginRequiredMixin, ListView):
#     model = EmailStatistics
#     template_name = "email_statistics.html"
#
#     def get_queryset(self):
#         return EmailStatistics.objects.filter(user=self.request.user)

mailing/templates/home.html
{% extends 'client/base.html' %}
{% block title %} Главная {% endblock %}
{% block content %}
<h1 class="text-center">Сервис управления рассылками</h1>
<p>Общее количество рассылок: {{ total_mailings }}</p>
<p>Количество активных рассылок: {{ active_mailings }}</p>
<p>Количество уникальных получателей: {{ unique_recipients }}</p>
{% if user.is_authenticated %}
<h3>Статистика рассылок</h3>
<table>
    <thead>
        <tr>
            <th>Успешные попытки</th>
            <th>Неуспешные попытки</th>
            <th>Всего отправлено</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{ object.successful_attempts }}</td>
            <td>{{ object.failed_attempts }}</td>
            <td>{{ object.total_sent }}</td>
        </tr>
    </tbody>
</table>
{% else %}
    <p>Пожалуйста, <a href="{% url 'users:login' %}">войдите</a>, чтобы увидеть свою статистику.</p>
{% endif %}
{% endblock %}

mailing/templates/mailing_confirm_delete.html
{% extends 'client/base.html' %}
{% block title %} Удаление рассылки {% endblock %}
{% block content %}
 <div class="container h-100 d-flex align-items-center justify-content-center">
     <div class="row justify-content-center">
         <div class="col-6">
             <form class="row" method="post" enctype="multipart/form-data">
                 <div class="card text-center mt-2">
                     <div class="card-header">
                         <h5 class="card-title mt-2" style="min-height: 40px;">
                             Вы действительно хотите удалить рассылку "{{object.communication}}"?</h5>
                     </div>
                     <div class="card-body d-flex flex-column align-items-center justify-content-center">
                         {% csrf_token %}
                     </div>
                     <div class="mt-auto">
                         <a class="btn btn-primary" href="{% url 'mailing:mailing_detail' mailing.pk %}" role="button">Отмена</a>
                         <button type="submit" class="btn btn-danger ">Удалить</button>
                     </div>
                 </div>
             </form>
         </div>
     </div>
 </div>
{% endblock %}

mailing/templates/mailing_detail.html
{% extends 'client/base.html' %}
{% block title %}Информация о рассылке | {{ object.communication.name }}{% endblock %}
{% block content %}

<h1 class="text-center">Рассылка: {{ object.communication.topic }}</h1>
<p class="mt-3">Статус: {{ object.status }}</p>
<p>Время первой отправки: {{ object.first_send_time }}</p>
<p>Время завершения: {{ object.end_time }}</p>

<div class="mt-4">
    <a class="btn btn-outline-primary" href="{% url 'mailing:mailing_update' object.pk %}" role="button">Редактировать</a>
    <a class="btn btn-outline-danger" href="{% url 'mailing:mailing_delete' object.pk %}" role="button">Удалить</a>
</div>

<p>Последнее изменение: {{ object.updated_at }}</p>
<p>Добавлено: {{ object.created_at }}</p>

{% endblock %}

mailing/templates/mailing_form.html
{% extends 'client/base.html' %}
{% block title %} {% if object %}
Редактирование рассылки
{% else %}
Новая рассылка
{% endif %} {% endblock %}
{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header text-center">
                    <h5 class="card-title mt-2" style="min-height: 40px;">
                        {% if object %}
                        Редактирование рассылки
                        {% else %}
                        Новая рассылка
                        {% endif %}
                    </h5>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Сохранить</button>
                        <button type="button" class="btn btn-danger ml-2">
                            <a class="text-white" href="{% url 'mailing:mailing_list' %}">Отмена</a>
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing_list.html
{% extends 'client/base.html' %}
{% load static %}
{% block title %} Рассылки {% endblock %}
{% block content %}
<h1 class="text-center mt-3">Список рассылок</h1>
{% if user.is_authenticated %}
{% if object_list %}
<table class="table table-bordered">
    <thead>
    <tr>
        <th>Статус</th>
        <th>Тема</th>
        <th>Получатели</th>
        <th>Последнее изменение</th>
        <th>Действия</th>
    </tr>
    </thead>
    <tbody>
    {% for mailing in object_list %}
    <tr>
        <td>{{ mailing.status }}</td>
        <td>{{ mailing.communication.topic|truncatewords:10 }}</td>
        <td>{{ mailing.client.count }} получателей</td>
        <td>
            <small>Последнее изменение: {{ mailing.updated_at|timesince }} назад</small>
            <span class="text-primary" style="cursor: pointer;"
                  onclick="window.location.href='{% url 'mailing:mailing_detail' mailing.pk %}'">Подробнее</span>
        </td>
        <td>
            <div class="btn-group" role="group">
                <a class="btn btn-info" href="{% url 'mailing:mailing_update' mailing.pk %}">Редактировать</a>
                <form action="{% url 'mailing:mailing_delete' mailing.pk %}" method="post" style="display:inline;">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Удалить</button>
                </form>
                <form action="{% url 'mailing:send_mailing' mailing.pk %}" method="post" style="display:inline;">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-success">Отправить</button>
                </form>
            </div>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% else %}
<p class="text-center">Cписок рассылок пуст.</p>
{% endif %}
<div class="text-center mt-3">
    <a class="btn btn-secondary text-white" href="{% url 'mailing:mailing_create' %}">Создать новую рассылку</a>
</div>
{% else %}
    <p>Пожалуйста, <a href="{% url 'users:login' %}">войдите</a>, чтобы увидеть свою рассылку.</p>
{% endif %}
{% endblock %}

mailing/templates/result.html
{% extends 'client/base.html' %}
{% block title %}Результат рассылки {{ object.communication.name }}{% endblock %}
{% block content %}
<h1>Результат рассылки</h1>
    <p>{{ message }}</p>
    <a href="{% url 'mailing:mailing_list' %}">Вернуться к списку рассылок</a>
{% endblock %}